package sk.wlio.sx2.exception;

public enum SxExTyp {
    END_OF_FILE,
    UNEXPECTED_PREFIX,
    CAKAL_ZATVORKU,
    CAKAL_ZATVORKU_ALEBO_CIARKU,
    CAKAL_OPERATOR,
    CAKAL_OPERATOR_POROVNANIA,
    CAKAL_CISLO,
    CAKAL_CIARKU,
    PRAZDNE_SLOVO,
    CAKAL_INSTRUKCIU,
    CAKAL_VRAT,
    CAKAL_AK,
    ZLY_DATOVY_TYP,
    ZLY_NAZOV_PRIKAZU,
    CAKAL_DEKLARACIU_PRIKAZU,
    CAKAL_DATOVY_TYP,
    CAKAL_DATOVU_HODNOTU,
    CAKAL_BOOL,
    CAKAL_DEKLARACIU_PRIKAZU_ALEBO_PREMENNEJ,
    NEZNAMY_PRIKAZ,
    NESPRAVNY_POCET_PARAMETROV,
    NEZNAMA_PREMENNA,
    CAKAL_INSTRUKCIA_SLOVO,
    PREMENNA_UZ_EXISTUJE,
    PRIKAZ_UZ_EXISTUJE
}
